-- Create Products Table
create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric not null,
  image text,
  category text,
  description text,
  features text[],
  specs jsonb,
  stock integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS) for Products
alter table public.products enable row level security;

-- Create Policy for Products (Public Read)
create policy "Public products are viewable by everyone"
  on public.products for select
  using ( true );

-- Create Policy for Products (Public Insert/Update/Delete for Admin Dashboard compatibility)
-- Note: In a real production app, you should restrict this to authenticated admin users.
create policy "Public can modify products"
  on public.products for all
  using ( true );

-- Create Profiles Table (extends auth.users)
create table public.profiles (
  id uuid references auth.users not null primary key,
  name text,
  email text,
  phone text,
  avatar text,
  address text,
  city text,
  zip text,
  updated_at timestamp with time zone
);

-- Enable RLS for Profiles
alter table public.profiles enable row level security;

-- Create Policy for Profiles (Users can view/edit their own profile)
create policy "Users can view own profile"
  on public.profiles for select
  using ( auth.uid() = id );

create policy "Users can update own profile"
  on public.profiles for update
  using ( auth.uid() = id );

create policy "Users can insert own profile"
  on public.profiles for insert
  with check ( auth.uid() = id );

-- Create Orders Table
create table public.orders (
  id text primary key, -- keeping text id to match current frontend logic
  user_id uuid references auth.users, -- nullable for guest orders
  date timestamp with time zone default timezone('utc'::text, now()) not null,
  items jsonb not null,
  total numeric not null,
  status text not null,
  shipping_details jsonb not null,
  payment_method text,
  transaction_id text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for Orders
alter table public.orders enable row level security;

-- Create Policy for Orders (Public Read/Write for Admin Dashboard compatibility)
-- Note: In a real production app, you should restrict this to authenticated users and admins.
create policy "Public can view and modify orders"
  on public.orders for all
  using ( true );

-- Seed Data for Products
INSERT INTO public.products (name, price, category, image, description, features, specs, stock) VALUES
('Ultra HD Smart Watch', 4500.00, 'Wearables', 'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?auto=format&fit=crop&q=80&w=800', 'Experience the future on your wrist with the Ultra HD Smart Watch. Featuring a crystal-clear AMOLED display, comprehensive health tracking, and seamless connectivity, it''s the perfect companion for your active lifestyle.', ARRAY['1.78-inch AMOLED Display', '24/7 Heart Rate Monitoring', 'SpO2 Blood Oxygen Tracking', '10-Day Battery Life', 'IP68 Water Resistance'], '{"Display": "1.78\" AMOLED", "Battery": "350mAh", "Connectivity": "Bluetooth 5.2", "Water Resistance": "IP68", "Compatibility": "Android & iOS"}', 50),
('Noise Cancelling Earbuds', 3200.00, 'Audio', 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&q=80&w=800', 'Immerse yourself in pure sound with our Noise Cancelling Earbuds. Advanced active noise cancellation blocks out the world, while high-fidelity drivers deliver rich, balanced audio.', ARRAY['Active Noise Cancellation (ANC)', 'Transparency Mode', '30 Hours Total Playtime', 'Dual Microphones for Clear Calls', 'Touch Controls'], '{"Driver Size": "10mm", "Battery Life": "6h (Earbuds) + 24h (Case)", "Charging": "USB-C & Wireless", "Bluetooth": "5.3", "Weight": "4.5g per earbud"}', 120),
('Mechanical Gaming Keyboard', 5500.00, 'Gaming', 'https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?auto=format&fit=crop&q=80&w=800', 'Dominate the competition with our Mechanical Gaming Keyboard. Equipped with tactile mechanical switches and customizable RGB lighting, it offers precision and style for every gamer.', ARRAY['Tactile Mechanical Switches', 'Per-Key RGB Lighting', 'Aircraft-Grade Aluminum Frame', 'Detachable USB-C Cable', 'N-Key Rollover'], '{"Switch Type": "Blue / Red / Brown", "Key Layout": "87-Key TKL", "Backlight": "RGB (16.8M Colors)", "Cable Length": "1.8m Braided", "Dimensions": "360 x 135 x 35 mm"}', 30),
('20000mAh Fast Power Bank', 2100.00, 'Accessories', 'https://images.unsplash.com/photo-1609592424302-16c7ae3b4605?auto=format&fit=crop&q=80&w=800', 'Never run out of power again. This 20000mAh Power Bank supports fast charging for multiple devices simultaneously, ensuring you stay connected wherever you go.', ARRAY['20000mAh High Capacity', '22.5W Fast Charging', 'Dual USB-A & Single USB-C Output', 'Digital LED Power Display', 'Compact & Portable Design'], '{"Capacity": "20000mAh", "Input": "USB-C / Micro-USB", "Output": "2x USB-A, 1x USB-C", "Fast Charge": "PD 3.0 & QC 3.0", "Weight": "400g"}', 200),
('Wireless Gaming Mouse', 2800.00, 'Gaming', 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&q=80&w=800', 'Experience lag-free gaming with our Wireless Gaming Mouse. High-precision sensor and ergonomic design give you the edge you need in competitive play.', ARRAY['16000 DPI Optical Sensor', '1ms Response Time', '7 Programmable Buttons', 'RGB Lighting Zones', '50-Hour Battery Life'], '{"Sensor": "Optical", "DPI": "Up to 16000", "Polling Rate": "1000Hz", "Connection": "2.4GHz Wireless", "Weight": "95g"}', 75),
('Portable Bluetooth Speaker', 3500.00, 'Audio', 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&q=80&w=800', 'Bring the party anywhere with this Portable Bluetooth Speaker. Powerful bass, clear highs, and a rugged waterproof design make it perfect for outdoor adventures.', ARRAY['360° Surround Sound', 'IPX7 Waterproof Rating', '12-Hour Playtime', 'Built-in Microphone', 'Stereo Pairing Mode'], '{"Output Power": "20W", "Battery": "4000mAh", "Bluetooth": "5.0", "Waterproof": "IPX7", "Dimensions": "180 x 70 x 70 mm"}', 40),
('4K Action Camera', 12500.00, 'Cameras', 'https://images.unsplash.com/photo-1564466019553-37848e8c7487?auto=format&fit=crop&q=80&w=800', 'Capture life''s most thrilling moments in stunning 4K. This Action Camera is built tough and packed with features like image stabilization and Wi-Fi connectivity.', ARRAY['4K Ultra HD Video at 60fps', 'Electronic Image Stabilization (EIS)', 'Dual Screen Display', 'Waterproof up to 30m (with case)', 'Wi-Fi & App Control'], '{"Video Resolution": "4K/60fps, 1080p/240fps", "Photo Resolution": "20MP", "Lens": "170° Wide Angle", "Battery": "1350mAh Removable", "Storage": "MicroSD up to 128GB"}', 15),
('VR Headset Pro', 25000.00, 'VR/AR', 'https://images.unsplash.com/photo-1622979135225-d2ba269fb1bd?auto=format&fit=crop&q=80&w=800', 'Step into new worlds with the VR Headset Pro. High-resolution displays and precise tracking deliver an immersive virtual reality experience like no other.', ARRAY['High-Resolution LCD Displays', 'Inside-Out Tracking', 'Comfortable Ergonomic Strap', 'Built-in 3D Audio', 'PC VR Compatible'], '{"Resolution": "1832 x 1920 per eye", "Refresh Rate": "90Hz / 120Hz", "FOV": "100 Degrees", "Processor": "XR2 Platform", "Storage": "128GB / 256GB"}', 8);
